root: true
env:
  browser: true
  node: true
  es6: true
  commonjs: true
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 2019
  sourceType: module
extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/recommended'
rules:
# Fixable
  curly:
    - error
    - multi-line
  no-extra-parens: off
  dot-location: error
  dot-notation: error
  eqeqeq: error
  no-else-return: error
  no-extra-bind: error
  no-extra-label: error
  no-floating-decimal: error
  no-implicit-coercion: error
  no-multi-spaces: error
  no-useless-return: error
  wrap-iife: off
  yoda: off
  strict:
    - error
    - never
  no-undef-init: error
  array-bracket-newline:
    - error
    - consistent
  array-bracket-spacing: error
  array-element-newline:
    - error
    - consistent
  block-spacing:
    - error
    - always
  brace-style:
    - error
    - 1tbs
    - allowSingleLine: true
  capitalized-comments: off
  comma-dangle:
    - error
    - always-multiline
  comma-spacing: error
  comma-style:
    - error
    - last
  computed-property-spacing: error
  eol-last: error
  func-call-spacing: error
  implicit-arrow-linebreak: error
  indent:
    - error
    - 2
  jsx-quotes: error
  key-spacing: error
  keyword-spacing:
    - error
    - after: true
      before: true
  linebreak-style:
    - error
    - unix
  lines-around-comment: error
  lines-between-class-members: error
  multiline-comment-style: off
  new-parens: error
  newline-per-chained-call: error
  no-lonely-if: off
  no-multiple-empty-lines:
    - error
    - max: 3
  no-trailing-spaces: error
  no-unneeded-ternary: warn
  no-whitespace-before-property: error
  nonblock-statement-body-position: error
  object-curly-newline:
    - error
    - minProperties: 3
      consistent: true
  object-curly-spacing:
    - error
    - always
  object-property-newline: error
  one-var:
    - error
    - let: never
      const: never
      separateRequires: true
  one-var-declaration-per-line: error
  operator-assignment: error
  operator-linebreak: error
  padded-blocks: off
  prefer-object-spread: error
  quote-props: off
  quotes:
    - error
    - single
  semi:
    - error
    - always
  semi-spacing: error
  semi-style: error
  sort-vars: off
  space-before-blocks: off
  space-before-function-paren: off
  space-in-parens:
    - error
    - never
  space-infix-ops: error
  space-unary-ops: error
  spaced-comment:
    - error
    - always
  switch-colon-spacing: error
  template-tag-spacing: error
  unicode-bom:
    - error
    - never
  wrap-regex: error
  arrow-body-style: error
  arrow-parens:
    - error
    - as-needed
  arrow-spacing: error
  generator-star-spacing: error
  no-confusing-arrow: error
  no-useless-computed-key: error
  no-useless-rename: error
  no-var: error
  object-shorthand: error
  prefer-arrow-callback: off
  prefer-const: off
  prefer-destructuring: error
  prefer-numeric-literals: error
  prefer-template: error
  rest-spread-spacing: error
  sort-imports:
    - error
    - ignoreCase: true
      ignoreDeclarationSort: true
      ignoreMemberSort: true
  template-curly-spacing: error 
  yield-star-spacing: error
  padding-line-between-statements:
    - error
    - blankLine: always
      prev:
        - block-like
      next: '*'
    - blankLine: always
      prev:
        - let
        - const
      next: block-like
    - blankLine: always
      prev: '*'
      next:
        - return
        - block-like

# Rest
  accessor-pairs: off
  array-callback-return: error
  block-scoped-var: error
  callback-return: error
  camelcase: error
  class-methods-use-this: error
  complexity: error
  consistent-return: error
  consistent-this: error
  default-case: error
  func-name-matching: error
  func-names:
    - error
    - always
  func-style: error
  function-paren-newline:
    - error
    - minItems: 4
  global-require: error
  guard-for-in: error
  handle-callback-err: error
  id-blacklist: error
  id-length: off
  id-match: error
  init-declarations: off
  line-comment-position: error
  max-depth: error
  max-len:
    - error
    - ignoreTemplateLiterals: true
      ignoreStrings: true
      ignoreUrls: true
      ignorePattern: "<.+"
  max-lines: error
  max-nested-callbacks: error
  max-params: error
  max-statements: off
  max-statements-per-line: error
  multiline-ternary: off
  new-cap: error
  no-alert: error
  no-array-constructor: error
  no-await-in-loop: error
  no-bitwise: error
  no-buffer-constructor: error
  no-caller: error
  no-continue: error
  no-div-regex: error
  no-duplicate-imports: error
  no-empty-function: error
  no-eq-null: error
  no-eval: error
  no-extend-native: error
  no-implicit-globals: error
  no-implied-eval: error
  no-inline-comments: error
  no-invalid-this: error
  no-iterator: error
  no-label-var: error
  no-labels: error
  no-lone-blocks: error
  no-loop-func: error
  no-magic-numbers: off
  no-mixed-operators: error
  no-mixed-requires: error
  no-multi-assign: error
  no-multi-str: error
  no-negated-condition: off
  no-nested-ternary: error
  no-new: error
  no-new-func: error
  no-new-object: error
  no-new-require: error
  no-new-wrappers: error
  no-octal-escape: error
  no-param-reassign: error
  no-path-concat: error
  no-plusplus: error
  no-process-env: error
  no-process-exit: error
  no-proto: error
  no-prototype-builtins: error
  no-restricted-globals: error
  no-restricted-imports: error
  no-restricted-modules: error
  no-restricted-properties: error
  no-restricted-syntax: error
  no-return-assign: error
  no-return-await: error
  no-script-url: error
  no-self-compare: error
  no-sequences: error
  no-shadow: error
  no-shadow-restricted-names: error
  no-sync: error
  no-tabs: error
  no-template-curly-in-string: error
  no-ternary: off
  no-throw-literal: error
  no-undefined: error
  no-underscore-dangle: error
  no-unmodified-loop-condition: error  
  no-unused-expressions: off
  no-use-before-define: error
  no-useless-call: error
  no-useless-concat: error
  no-useless-constructor: error
  no-void: error
  no-warning-comments: error
  no-with: error
  prefer-promise-reject-errors: error
  prefer-rest-params: error
  prefer-spread: error
  radix:
    - error
    - as-needed
  require-await: error
  sort-keys: off
  symbol-description: error
  vars-on-top: error

  # Plugins
  '@typescript-eslint/no-var-requires': off
  '@typescript-eslint/no-explicit-any': off
  '@typescript-eslint/no-non-null-assertion': off
  '@typescript-eslint/ban-ts-comment': off
