## Site Variables ##
baseURL: https://caylapanitzlpc.com
title: Cayla Panitz, LPC
description: Awesome therapist.
author:
  name: Cayla Panitz

## Params ##
params:
  # Theme
  theme: &thm "#ffeb8c"

  # Favicons
  favicons:
    - rel: apple-touch-icon
      href: img/apple-touch-icon.png
    - rel: icon
      href: img/favicon-192x192.png
      type: image/png
      sizes: 192x192
    - rel: icon
      href: img/favicon-96x96.png
      type: image/png
      sizes: 96x96
    - rel: icon
      href: img/favicon.svg
      type: image/svg+xml
    - rel: mask-icon
      href: img/pinned-tab.svg
      color: *thm

  # Browserconfig
  bconfig:
    s150: img/Square150x150Logo.scale-100.png
    s310: img/Square310x310Logo.scale-100.png
    w310: img/Wide310x150Logo.scale-100.png

  # Manifest
  manifest:
    s192: img/android-chrome-192x192.png
    s256: img/android-chrome-256x256.png
  
  # Image
  image:
    src: img/cayla-panitz-og.png
    type: image/png
    width: 1200
    height: 628

  # License
  license:
    name: Licensed Professional Counselor
    from: State of Oregon Board of Professional Counselors and Therapists
    name_url: https://hrlb.oregon.gov/oblpct/licenseelookup/detail.asp?num=133599
    from_url: https://www.oregon.gov/OBLPCT/Pages/index.aspx


## Markup ##
markup:
  goldmark:
    parser:
      autoHeadingID: false
    renderer:
      unsafe: true


## Sitemap ##
sitemap:
  changefreq: weekly
  filename: sitemap.xml
  priority: 0.9


## Build ##
enableGitInfo: true
enableRobotsTXT: true
disableHugoGeneratorInject: true
disableKinds:
  - taxonomy
  - taxonomyTerm
  - RSS
enableEmoji: true
relativeURLs: true
