[build]
base = "/"
publish = "/public"
command = "npm run build"

[build.environment]
NODE_VERSION = "15.1.0"
HUGO_VERSION = "0.78.1"
NODE_ENV = "production"


[[headers]]
for = "/*"

[headers.values]
cache-control = '''
  public,
  max-age=5256000'''
