[build]
base = "/"
publish = "/public"
command = "npm run build"

[build.environment]
NODE_VERSION = "15.3.0"
HUGO_VERSION = "0.79.0"
NODE_ENV = "production"


[[headers]]
for = "/*"

[headers.values]
cache-control = '''
  public,
  max-age=5256000'''
